// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-oKa8XVj-_YUdUK_E7ji0E52DrGi7yYI',
    appId: '1:1046364438419:web:3502ac2e4f6e172ed0f266',
    messagingSenderId: '1046364438419',
    projectId: 'todoapp-34321',
    authDomain: 'todoapp-34321.firebaseapp.com',
    storageBucket: 'todoapp-34321.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDe0dwe0V8EHO8GCOqIpf97Y9p2APHeVw',
    appId: '1:1046364438419:android:f80a99010a73369ed0f266',
    messagingSenderId: '1046364438419',
    projectId: 'todoapp-34321',
    storageBucket: 'todoapp-34321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYxIsvdiu5X1MyA9sY94tzfUIJ1UDXcks',
    appId: '1:1046364438419:ios:7ef207eeee7664b2d0f266',
    messagingSenderId: '1046364438419',
    projectId: 'todoapp-34321',
    storageBucket: 'todoapp-34321.appspot.com',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAYxIsvdiu5X1MyA9sY94tzfUIJ1UDXcks',
    appId: '1:1046364438419:ios:df8c5046d6eff501d0f266',
    messagingSenderId: '1046364438419',
    projectId: 'todoapp-34321',
    storageBucket: 'todoapp-34321.appspot.com',
    iosBundleId: 'com.example.todoApp.RunnerTests',
  );
}
