// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMhWHTFxWHuI8zD8iy_1gAjdJuJvuEdFU',
    appId: '1:1045618807966:web:bb8cc25533c7506a88d78f',
    messagingSenderId: '1045618807966',
    projectId: 'weatherapp-6e77d',
    authDomain: 'weatherapp-6e77d.firebaseapp.com',
    storageBucket: 'weatherapp-6e77d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnLCli3ljrO7Dq6gL5xU84A07HwIp7J_8',
    appId: '1:1045618807966:android:68f5e50dd27ddfa288d78f',
    messagingSenderId: '1045618807966',
    projectId: 'weatherapp-6e77d',
    storageBucket: 'weatherapp-6e77d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB52oL35CJY0IM6gKD4x_YqR0v8mNTIqq8',
    appId: '1:1045618807966:ios:75a45b886ba9e84488d78f',
    messagingSenderId: '1045618807966',
    projectId: 'weatherapp-6e77d',
    storageBucket: 'weatherapp-6e77d.appspot.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB52oL35CJY0IM6gKD4x_YqR0v8mNTIqq8',
    appId: '1:1045618807966:ios:fbdfd947b042df5588d78f',
    messagingSenderId: '1045618807966',
    projectId: 'weatherapp-6e77d',
    storageBucket: 'weatherapp-6e77d.appspot.com',
    iosBundleId: 'com.example.weatherApp.RunnerTests',
  );
}
